"""Add user image url to User model

Revision ID: 55fb2a2ae586
Revises: 92bf4ad7346f
Create Date: 2021-09-09 08:01:17.365660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55fb2a2ae586'
down_revision = '92bf4ad7346f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_image_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_image_url')
    # ### end Alembic commands ###
